mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('sentinel.urls', namespace='sentinel')),
    path('cnc/', include('cnc.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 
]

sentinel/urls.py
from django.urls import path

from . import views

app_name = 'sentinel'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('video_feed', views.video_feed, name='video_feed'),
    path('generalreports/', views.generalReports, name="generalReports"),
    path('incidentlist/', views.incidentList, name="incidentList"),
    path('incidentreport/', views.incidentReport, name="incidentReport"),
    path('notifications/', views.notifications, name="notifications"),
]

sentinel/models.py
from django.db import models
from datetime import datetime
from mysite import settings

# Create your models here.
class end_user(models.Model):
    email = models.EmailField(primary_key = True, unique = True)
    firstName = models.CharField(max_length = 30)
    lastName = models.CharField(max_length = 30)
    accessID = models.ForeignKey('access_lvl', on_delete = models.PROTECT)
    password = models.CharField(max_length = 50)
    faceImgDir = models.FilePathField(path = settings.USER_FACE_DIR, allow_files=False, allow_folders=True, blank = True)

class access_lvl(models.Model):
    accessID = models.AutoField(primary_key = True)
    accessName = models.CharField(max_length = 20)

class activity_log(models.Model):
    activityID = models.AutoField(primary_key = True)
    email = models.ForeignKey('end_user', on_delete = models.PROTECT, blank=True, null=True)
    firstSeen = models.DateTimeField(default = datetime.now)
    lastSeen = models.DateTimeField()
    faceCaptureDir = models.FilePathField(path = settings.FACE_CAPTURE_DIR, allow_files=False, allow_folders=True)
    clipDir = models.FilePathField(path = settings.CLIP_DIR, allow_files=False, allow_folders=True)

class notification(models.Model):
    notifID = models.AutoField(primary_key = True)
    notifType = models.CharField(max_length = 20)
    notifDetails = models.CharField(max_length = 300)
    notifImgDir = models.FilePathField(path = settings.NOTIF_IMG_DIR, allow_files=False, allow_folders=True)
    isApproved = models.BooleanField(default = False)

class notification_recipient(models.Model):
    recipientID = models.AutoField(primary_key = True)
    accessID = models.ForeignKey('access_lvl', on_delete = models.PROTECT)
    notifID = models.ForeignKey('notification', on_delete = models.PROTECT)

class audit_log(models.Model):
    auditID = models.AutoField(primary_key = True)
    email = models.ForeignKey('end_user', on_delete = models.PROTECT, blank=True, null=True)
    notifID = models.IntegerField(blank=True, null=True)
    timestamp = models.DateTimeField()
    userAction = models.CharField(max_length = 100)

sentinel/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import StreamingHttpResponse
from django.forms.models import model_to_dict

# Python
import datetime as dt

# Utilities
from .camera import video_camera, generate

# Ploty
from plotly.offline import plot
import plotly.graph_objs as go

# Models
from .models import end_user

# Global Variables
SESSION_TIMEOUT = (60*5)
cam = video_camera()

# Created Views
def index(request):     # to Login Page
    request.session.set_expiry(SESSION_TIMEOUT)
    return render(request, 'sentinel/index.html')

def home(request):      # to Home Page
    valid = {}
    if request.method == 'POST':
        valid['email'] = request.POST['email']
        valid['password'] = request.POST['pass']
    else: # gets session variables
        valid = check_session(request)

    if valid:
        if end_user.objects.filter(email = valid['email']).exists(): # validation
            temp_user = end_user.objects.get(email = valid['email'])
            if valid['password'] == temp_user.password:
                request.session['user'] = model_to_dict(temp_user)
                request.session.set_expiry(SESSION_TIMEOUT)
                return render(request, 'sentinel/home.html')
            else:
                error_msg = 'Invalid Password'
        else:
            error_msg = 'Email does not Exist'
    else:
        error_msg = 'Session has Expired'

    context = {
        'error_msg': error_msg,
    }
    return render(request, 'sentinel/index.html', context)

def generalReports(request):
    valid = check_session(request)
    if valid:
        Incidents = go.Scatter(
            x=[dt.date(2017, 1, 1), dt.date(2017, 1, 3), dt.date(2017, 1, 3)],
            y=[dt.time(8, 0, 0), dt.time(12, 0, 0), dt.time(16, 0, 0)],
            mode='markers',
            name='Incident',
        )

        fig = go.Figure([Incidents])
        fig.update_xaxes(tickformat='%m/%d/%y', tickangle=45)
        fig.update_yaxes(range=[dt.time(0,0,0), dt.time(23,0,0)])

        plot_div = plot(fig, output_type='div')

        context = {
            'plot_div': plot_div,
        }
        request.session.set_expiry(SESSION_TIMEOUT)
        return render(request, 'sentinel/generalReports.html', context)
    else:
        error_msg = 'Session has Expired'

    context = {
        'error_msg': error_msg,
    }
    return render(request, 'sentinel/index.html', context)

def incidentList(request):
    valid = check_session(request)
    if valid:
        request.session.set_expiry(SESSION_TIMEOUT)
        return render(request, 'sentinel/incidentList.html')
    else:
        error_msg = 'Session has Expired'

    context = {
        'error_msg': error_msg,
    }
    return render(request, 'sentinel/index.html', context)

def incidentReport(request):
    valid = check_session(request)
    if valid:
        request.session.set_expiry(SESSION_TIMEOUT)
        return render(request, 'sentinel/incidentReport.html')
    else:
        error_msg = 'Session has Expired'

    context = {
        'error_msg': error_msg,
    }
    return render(request, 'sentinel/index.html', context)

def notifications(request):
    valid = check_session(request)
    if valid:
        request.session.set_expiry(SESSION_TIMEOUT)
        return render(request, 'sentinel/notifs.html')
    else:
        error_msg = 'Session has Expired'

    context = {
        'error_msg': error_msg,
    }
    return render(request, 'sentinel/index.html', context)

def video_feed(request):
    try:
        return StreamingHttpResponse(generate(cam), content_type="multipart/x-mixed-replace;boundary=frame")
    except:  # This is bad! replace it with proper handling
        pass

# helper functions
def check_session(request):
    context = {}
    try:
        context['email'] = request.session['user']['email']
        context['password'] = request.session['user']['password']
    except KeyError as ke: # no session
        print('[WARNING] Session not valid')

    return context

sentinel/templates/sentinel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock title %}</title>

  <link rel="icon" href="{% static 'images/eye.png' %}" type="image/x-icon">
  <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/index_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/incident_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/gen_reports_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/incident_report_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/log_in.css' %}">
  <link rel="stylesheet" href="{% static 'css/notif_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/sidebar_extra_styles.css' %}">
</head>
<body>
    {% block body %}{% endblock body %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

sentinel/templates/sentinel/generalReports.html
{% extends 'sentinel/base.html' %}
{% block title %}Sentinel · GeneralReports{% endblock title %}

{% block body %}
	<div class="wrapper d-flex align-items-stretch">
		<nav id="sidebar">
			<div class="p-4 pt-5">
	  		<h3 id="sidebarTitle"><span> <b>SENTINEL</b> </span> </h3>
        <ul class="list-unstyled components mb-5">
          <li>
            <a href="{% url 'sentinel:home' %}">Live Feed</a>
          </li>

          <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Reports</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
              <li class="active">
                  <a href="{% url 'sentinel:generalReports' %}">General Reports</a>
              </li>
              <li>
                  <a href="{% url 'sentinel:incidentList' %}">Incident Reports</a>
              </li>
            </ul>
          </li>

          <li>
            <a href="{% url 'sentinel:notifications' %}">Notifications</a>
          </li>
        </ul>

        <div class="footer">
          <p>SENTINEL</p>
        </div>

      </div>
  	</nav>

    <!-- Page navbar  -->
    <div id="content" class="p-4 p-md-3">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

          <button type="button" id="sidebarCollapse" class="btn btn-primary">
            <i class="fa fa-bars"></i>
            <span class="sr-only">Toggle Menu</span>
          </button>
        </div>
      </nav>

      <div class="contentReps">
        <div class="container">
            <h4 class="text-dark pb-1">General Report</h4>
            <hr>
    <div class="card text-center text-dark">
      <!-- DATE INPUT -->
      <div class="card-header">
        <h6>Input date</h6>
      </div>
      <div class="card-body inptField align">
        <label for="genFrm">From: </label>
        <input type="date" name="genFrm" value="">
        <label for="genTo">To: </label>
        <input type="date" name="genTo" value=""><br>
        <div class="pt-3">
            <button class="genBtn" type="button" name="button">Generate</button>
        </div>
      </div>
    </div><br>
    <!-- GRAPH -->
    <div class="card text-dark">
      <div class="card-header">
        Graph
      </div>
      <div class="card-body">
				{% autoescape off %}
			  {{ plot_div }}
			  {% endautoescape %}
      </div>
    </div>
    <!-- LIST OF PEOPLE WHO ACCESSED THE ROOM -->
    <hr style="color:white;">
    <div class="table-responsive mb-1">
      <table class="table table-bordered text-center">
        <thead class="thead-dark">
          <tr>
            <th colspan="5" class="align-middle">LIST OF PEOPLE WHO ACCESSED THE ROOM</th>
          </tr>
        </thead>
        <thead class="thead-light">
          <tr>
            <!--th scope="col" class="align-middle">Image</th-->
            <th scope="col" class="align-middle">Name</th>
            <!--th scope="col" class="align-middle">ID</th-->
            <th scope="col" class="align-middle">No. of entry</th>
            <th scope="col" class="align-middle">Time of last access</th>
          </tr>
        </thead>
        <tbody class="bg-light">
          <tr>
            <!--td class="align-middle"><img src="main/images/user.png" alt="Intruder Image" class="img-fluid rounded" height="60" width="60"></td-->
            <td class="align-middle">Ernest Fernandez</td>
            <!--td class="align-middle">201701058</td-->
            <td class="align-middle">10</td>
            <td class="align-middle">10:00 AM - 10:05 AM<br/>17/11/2019</td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- DOWNLOAD -->
    <div class="text-center mb-4">
      <button class="downloadBtn" type="button" class="btn btn-info">DOWNLOAD</button>
    </div>
  </div>


    </div>
	</div>
{% endblock body %}

sentinel/templates/sentinel/home.html
{% extends 'sentinel/base.html' %}
{% block title %}Sentinel · Home{% endblock title %}

{% block body %}
	<div class="wrapper d-flex align-items-stretch">
		<nav id="sidebar" class="">
			<div class="p-4 pt-5">
	  		<h3 id="sidebarTitle"><span> <b>SENTINEL</b> </span> </h3>
        <ul class="list-unstyled components mb-5">
          <li class="active">
            <a href="{% url 'sentinel:home' %}">Live Feed</a>
          </li>
          <li>
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Reports</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
              <li>
                  <a href="{% url 'sentinel:generalReports' %}">General Reports</a>
              </li>
              <li>
                  <a href="{% url 'sentinel:incidentList' %}">Incident Reports</a>
              </li>
            </ul>
          </li>
          <li>
            <a href="{% url 'sentinel:notifications' %}">Notifications</a>
          </li>
        </ul>
        <div class="footer">
          <p>SENTINEL</p>
        </div>

      </div>
  	</nav>

      <!-- Page navbar  -->
    <div id="content" class="p-4 p-md-3">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

          <button type="button" id="sidebarCollapse" class="btn btn-primary">
            <i class="fa fa-bars"></i>
            <span class="sr-only">Toggle Menu</span>
          </button>
        </div>
      </nav>
      <!-- Page Content-->
      <div class="mb-1">
        <div class="pageTitle">
          <h4 class="mb-2">LIVE FEED</h4>
        </div>
       <!-- <video width="100%" height="100%" autoplay="autoplay">
          <source src="http://192.168.0.24:8080">
        </video><br>-->
				<img src="{% url 'sentinel:video_feed' %}" class="img-fluid mb-5 mx-auto d-block"/>
			<button class="button" type="button" name="button" class="button">
        SEND ALERT
      </button>
    </div>
	</div>
</div>
{% endblock body %}

sentinel/templates/sentinel/incidentList.html
{% extends 'sentinel/base.html' %}
{% block title %}Sentinel · IncidentList{% endblock title %}

{% block body %}
		<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar">
				<div class="p-4 pt-5">
		  		<h3 id="sidebarTitle"><span> <b>SENTINEL</b> </span> </h3>
	        <ul class="list-unstyled components mb-5">
            <li>
              <a href="{% url 'sentinel:home' %}">Live Feed</a>
            </li>
	          <li class="active">
	            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Reports</a>
	            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href="{% url 'sentinel:generalReports' %}">General Reports</a>
                </li>
                <li class="active">
                    <a href="{% url 'sentinel:incidentList' %}">Incident Reports</a>
                </li>
	            </ul>
	          </li>
            <li>
              <a href="{% url 'sentinel:notifications' %}">Notifications</a>
            </li>
	        </ul>
	        <div class="footer">
            <p>SENTINEL</p>
	        </div>

	      </div>
    	</nav>

        <!-- Page navbar  -->
      <div id="content" class="p-4 p-md-3">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-primary">
              <i class="fa fa-bars"></i>
              <span class="sr-only">Toggle Menu</span>
            </button>
          </div>
        </nav>

        <!-- [Page Content]-->
        <!-- NOTE SHOULD WE DIFFERECNIATE IF A INCIDENT LIST IS EITHER USER SNET OR AN INTRUDER ALERT -->
        <h3 class="InciListTitle">INCIDENT LIST</h3>
        <table class="table table-striped table-dark">
          <thead>
            <tr>
              <th scope="col">Date and time</th>
              <th scope="col">Delete</th>
              <th scope="col">View</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">dd/mm/yyyy</th>
              <td> <button type="button" class="deleteButton">DELETE</button> </td>
              <td> <a href="{% url 'sentinel:incidentReport' %}"><button type="button" class="viewButton">VIEW</button> </td></a>
            </tr>
            <tr>
              <th scope="row">dd/mm/yyyy</th>
              <td> <button type="button" class="deleteButton">DELETE</button> </td>
              <td> <a href="{% url 'sentinel:incidentReport' %}"><button type="button" class="viewButton">VIEW</button> </td></a>
            </tr>
            <tr>
              <th scope="row">dd/mm/yyyy</th>
              <td> <button type="button" class="deleteButton">DELETE</button> </td>
              <td> <a href="{% url 'sentinel:incidentReport' %}"><button type="button" class="viewButton">VIEW</button> </td></a>
            </tr>
          </tbody>
        </table>

      </div>
		</div>
{% endblock body %}

sentinel/templates/sentinel/incidentReport.html
{% extends 'sentinel/base.html' %}
{% load static %}
{% block title %}Sentinel · IncidentReport{% endblock title %}

{% block body %}
		<div class="wrapper d-flex align-items-stretch">
      <nav id="sidebar">
        <div class="p-4 pt-5">
          <h3 id="sidebarTitle"><span> <b>SENTINEL</b> </span> </h3>
          <ul class="list-unstyled components mb-5">
            <li>
              <a href="{% url 'sentinel:home' %}">Live Feed</a>
            </li>
	          <li class="active">
	            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Reports</a>
	            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href="{% url 'sentinel:generalReports' %}">General Reports</a>
                </li>
                <li class="active">
                    <a href="{% url 'sentinel:incidentList' %}">Incident Reports</a>
                </li>
	            </ul>
	          </li>
            <li>
              <a href="{% url 'sentinel:notifications' %}">Notifications</a>
            </li>
          </ul>
          <div class="footer">
            <p>SENTINEL</p>
          </div>

        </div>
      </nav>

        <!-- Page navbar  -->
      <div id="content" class="p-4 p-md-3">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-primary">
              <i class="fa fa-bars"></i>
              <span class="sr-only">Toggle Menu</span>
            </button>
          </div>
        </nav>

        <!-- [Page Content]-->
        <div class="mb-1">
          <div class="pageTitle">
            <h4 class="mb-2">Incident Report</h4>
          </div>
          <!-- CLIP -->
          <div class="container incidentClip">
            <video c width="100%" height="100%" controls>
              <source src="https://www.youtube.com/watch?v=rTj4vUgyGxM&t=5s" type="video/mp4">
            </video><br>
            <!-- INTRUDERS -->
            <div class="intruderFaces">
              <div class="card">
                <div class="card-header">
                  <h5>INTRUDERS</h5>
                </div>
                <div class="card-body">
                  <img src="{% static 'images/person.png' %}" alt="" height="180" width="180">
                  <img src="{% static 'images/person.png' %}" alt="" height="180" width="180">
                  <img src="{% static 'images/person.png' %}" alt="" height="180" width="180">
                </div>
              </div>
            </div>
            <!-- Time in and time out-->
            <div class="card">
              <div class="card-header">
                <h5>Time in - Time out</h5>
              </div>
              <div class="card-body">
                TIME HERE
              </div>
            </div>
            <!-- Action taken -->
            <div class="card">
              <div class="card-header">
                <h5>Action Taken</h5>
              </div>
              <div class="card-body">
                <p>TEXT HERE</p>
              </div>
            </div>
            <!-- Remarks -->
            <div class="card">
              <div class="card-header">
                <h5>Remarks</h5>
              </div>
              <div class="card-body">
                <p>TEXT HERE</p>
              </div>
            </div>

            <!-- DOWNLOAD -->
            <div class="pt-3">
              <button class="downloadBtn" type="button" class="btn btn-info">DOWNLOAD</button>
            </div>
          </div>
        </div>


      </div>
		</div>
{% endblock body %}

sentinel/templates/sentinel/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Sentinel</title>
	<link rel="icon" href="{% static 'images/eye.png' %}" type="image/x-icon">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" href="{% static 'css/log_in.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" action="{% url 'sentinel:home' %}" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-26">
						Sentinel
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-eye"></i>
					</span>

					{% if error_msg %}
					<p class="text-danger mb-3">{{error_msg}}</p>
					{% endif %}
					
					<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
						<input class="input100" type="email" name="email">
						<span class="focus-input100" data-placeholder="Email"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="pass">
						<span class="focus-input100" data-placeholder="Password"></span>
					</div>

					<div class="container-login100-form-btn mb-5">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" type="submit" value="Submit">
								Login
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/log_in.js' %}"></script>

</body>
</html>

sentinel/templates/sentinel/notifs.html
{% extends 'sentinel/base.html' %}
{% load static %}
{% block title %}Sentinel · Notifications{% endblock title %}

{% block body %}
<div class="wrapper d-flex align-items-stretch">
  <nav id="sidebar">
    <div class="p-4 pt-5">
      <h3 id="sidebarTitle"><span> <b>SENTINEL</b> </span> </h3>
      <ul class="list-unstyled components mb-5">
        <li>
          <a href="{% url 'sentinel:home' %}">Live Feed</a>
        </li>
        <li>
          <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Reports</a>
          <ul class="collapse list-unstyled" id="homeSubmenu">
            <li>
                <a href="{% url 'sentinel:generalReports' %}">General Reports</a>
            </li>
            <li>
                <a href="{% url 'sentinel:incidentList' %}">Incident Reports</a>
            </li>
          </ul>
        </li>
        <li class="active">
          <a href="{% url 'sentinel:notifications' %}">Notifications</a>
        </li>
      </ul>
      <div class="footer">
        <p>SENTINEL</p>
      </div>

    </div>
  </nav>

        <!-- Page navbar  -->
      <div id="content" class="p-4 p-md-3">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-primary">
              <i class="fa fa-bars"></i>
              <span class="sr-only">Toggle Menu</span>
            </button>
          </div>
        </nav>

        <!-- [Page Content]-->
        <div class="notifsContainer">
          <h3>Alerts and Notifications</h3>

          <div class="card border-danger">
            <div class="card-header">
              Intruder Alert!
            </div>
            <div class="card-body">
              <h4 class="tileHeader">DATE AND TIME</h4>
              <img class="tileImg" src="{% static 'images/person.png' %}" alt="" width="80" height="80">
            </div>
          </div>
        </div><br>
        <!-- Access Request -->

        <!-- Intruder alert-->
        <div class="notifsContainer">
          <div class="card">
            <div class="card-header">
              Access Request
            </div>
            <div class="card-body">
              <img class="requestorImg" src="{% static 'images/person.png' %}" alt="" width="80" height="80">
              <p class="requestorRsn"><b>Reason:</b> Investigating for stolen underwear</p>
              <button class="AcceptBtn px-2" type="button" name="button">Accept</button>
              <button class="DenyBtn px-2" type="button" name="button">Deny</button>
            </div>
            <div class="card-footer text-muted">
              <span> <b>Name: Miguel de Veyra</b> </span> / date and time
            </div>
          </div>
        </div><br>
        <!-- User Warning -->
        <div class="notifsContainer">
          <div class="card border-warning">
            <div class="card-header">
              Access Request
            </div>
            <div class="card-body">
              <img class="requestorImg" src="{% static 'images/person.png' %}" alt="" width="80" height="80">
              <p class="requestorRsn"><b>Reason:</b> underwear found!</p>
            </div>
            <div class="card-footer text-muted">
              <span> <b>Name: Miguel de Veyra</b> </span> / date and time
            </div>
          </div>
        </div><br>

      </div>
		</div>
{% endblock body %}